import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MatchState, TeamId } from '../types';

export const generateJSON = (matchState: MatchState) => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(matchState, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `korfstat_match_${new Date(matchState.date || Date.now()).toISOString().split('T')[0]}.json`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
};

export const generatePDF = (matchState: MatchState) => {
    const doc = new jsPDF();
    const dateStr = new Date(matchState.date || Date.now()).toLocaleDateString();

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("KorfStat Pro - Match Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Date: ${dateStr}`, 14, 28);

    // --- Scoreboard ---
    const homeScore = matchState.events.filter(e => e.teamId === 'HOME' && e.result === 'GOAL').length;
    const awayScore = matchState.events.filter(e => e.teamId === 'AWAY' && e.result === 'GOAL').length;

    doc.setFillColor(245, 247, 250);
    doc.roundedRect(14, 35, 182, 30, 3, 3, 'F');

    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text(matchState.homeTeam.name, 20, 50);
    doc.text(matchState.awayTeam.name, 190, 50, { align: 'right' });

    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(`${homeScore} - ${awayScore}`, 105, 52, { align: 'center' });

    // --- Match Stats Generator Helper ---
    const getTeamStats = (teamId: TeamId) => {
        const team = teamId === 'HOME' ? matchState.homeTeam : matchState.awayTeam;
        return team.players.map(player => {
            const events = matchState.events.filter(e => e.playerId === player.id);
            const shots = events.filter(e => e.type === 'SHOT');
            const goals = shots.filter(e => e.result === 'GOAL');
            const rebounds = events.filter(e => e.type === 'REBOUND');
            const fouls = events.filter(e => e.type === 'FOUL');
            const percentage = shots.length > 0 ? Math.round((goals.length / shots.length) * 100) : 0;

            return [
                player.number,
                player.name,
                `${goals.length} / ${shots.length}`,
                `${percentage}%`,
                rebounds.length,
                fouls.length
            ];
        }).sort((a: any, b: any) => {
            const goalsA = parseInt(a[2].split(' / ')[0]);
            const goalsB = parseInt(b[2].split(' / ')[0]);
            return goalsB - goalsA;
        });
    };

    // --- Home Team Table ---
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`${matchState.homeTeam.name} Statistics`, 14, 80);

    autoTable(doc, {
        startY: 85,
        head: [['#', 'Player', 'Goals / Shots', '%', 'Rebounds', 'Fouls']],
        body: getTeamStats('HOME'),
        theme: 'grid',
        headStyles: { fillColor: [63, 81, 181] }, // Indigo
        styles: { fontSize: 10, cellPadding: 3 },
    });

    // --- Away Team Table ---
    // @ts-ignore
    let finalY = doc.lastAutoTable.finalY + 15;

    // Check for page break
    if (finalY > 250) {
        doc.addPage();
        finalY = 20;
    }

    doc.setFontSize(14);
    doc.text(`${matchState.awayTeam.name} Statistics`, 14, finalY);

    autoTable(doc, {
        startY: finalY + 5,
        head: [['#', 'Player', 'Goals / Shots', '%', 'Rebounds', 'Fouls']],
        body: getTeamStats('AWAY'),
        theme: 'grid',
        headStyles: { fillColor: [220, 38, 38] }, // Red
        styles: { fontSize: 10, cellPadding: 3 },
    });

    // --- Footer ---
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Generated by KorfStat Pro - Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    }

    doc.save(`korfstat_report_${new Date().toISOString().split('T')[0]}.pdf`);
};
